#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);


foreach my $event (qw ( nethserver-BackupPC4-update
                        nethserver-BackupPC-update
                    )) {
    templates2events("/etc/httpd/conf.d/default-virtualhost.inc", $event);
    templates2events("/etc/sudoers", $event);
    templates2events("/etc/httpd/conf.d/BackupPC.conf", $event);
    templates2events("/etc/BackupPC/pc/windowsxp-template.pl", $event);
    templates2events("/etc/BackupPC/pc/windows7-template.pl", $event);
    templates2events("/etc/BackupPC/pc/windows8-template.pl", $event);
    templates2events("/etc/BackupPC/pc/linux-template.pl", $event);
    templates2events("/usr/share/BackupPC/cygwin/rsyncd.secrets", $event);
    templates2events("/usr/share/BackupPC/cygwin/rsyncd.conf", $event);
    templates2events("/usr/share/BackupPC/cygwin/backuppc-fw-W7.bat", $event);
    templates2events("/usr/share/BackupPC/cygwin/backuppc-fw-xp.bat", $event);
    templates2events("/etc/nethserver/eorepo.conf", $event);

    event_actions($event,
    'initialize-default-databases' => '00',
    'backuppc-genkey' => '01',
    'nethserver-BackupPC-conf' => '10',
    'backuppc-upgrade-config_pl' => '20');

    event_services($event,
    'httpd' => 'reload',
    'backuppc'=>'restart');
}

my $event = 'trusted-networks-modify';
templates2events("/etc/httpd/conf.d/BackupPC.conf", $event);
event_services($event, 'httpd' => 'reload');
