#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);


# Event symlinks

my $event = 'nethserver-BackupPC-update';
templates2events("/etc/httpd/conf/httpd.conf", $event);
templates2events("/etc/sudoers", $event);
templates2events("/etc/httpd/bkpc-conf/httpd.conf", $event);

event_actions($event,
'initialize-default-databases' => '00',
'nethserver-BackupPC-conf' => '10',
'nethserver-BackupPC-service-conf' => '20',
'backuppc-genkey' => '30');

event_services($event,
'httpd' => 'reload',
'backuppc'=>'restart',
'httpd-bkpc'=>'restart');

