#!/usr/bin/perl -w

use esmith::ConfigDB;
my $db = esmith::ConfigDB->open_ro;
my $status = $db->get_prop('tt-rss','status')|| 'disabled';

if ($status eq 'enabled') {
system ('chkconfig httpd-bkpc on');
system ('/sbin/service tt-rss restart');
}

else {
system ('/sbin/service tt-rss stop');
system ('chkconfig httpd-bkpc off');
}

