#!/usr/bin/perl -w

use esmith::ConfigDB;
my $db = esmith::ConfigDB->open_ro;
my $status = $db->get_prop('httpd-bkpc','status')|| 'disabled';

if ($status eq 'enabled') {
system ('chkconfig httpd-bkpc on');
system ('/sbin/service httpd-bkpc restart');
}

else {
system ('/sbin/service httpd-bkpc stop');
system ('chkconfig httpd-bkpc off');
}

